/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programa;

/**
 *
 * @author miguel
 */
public class Programa extends javax.swing.JFrame {

    /**
     * Creates new form Programa
     */
    public Programa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListIdioma = new javax.swing.JList<>();
        jLabelTextoSelecIdioma = new javax.swing.JLabel();
        jLabelTextoSelecCat = new javax.swing.JLabel();
        jLabelTextoSelectCant = new javax.swing.JLabel();
        jRadioButtonProg = new javax.swing.JRadioButton();
        jRadioButtonMisc = new javax.swing.JRadioButton();
        jRadioButtonPun = new javax.swing.JRadioButton();
        jRadioButtonDark = new javax.swing.JRadioButton();
        jRadioButtonSpooky = new javax.swing.JRadioButton();
        jRadioButtonChrist = new javax.swing.JRadioButton();
        jLabelNumChistes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jListIdioma.setBackground(new java.awt.Color(102, 102, 102));
        jListIdioma.setBorder(null);
        jListIdioma.setForeground(new java.awt.Color(255, 255, 255));
        jListIdioma.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "en - English", "es - Español", "cs - Czech", "de - German", "fe - French", "pt - Portuguese" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListIdioma);

        jLabelTextoSelecIdioma.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabelTextoSelecIdioma.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoSelecIdioma.setText("1- Selecciona el Idioma de los chistes:");

        jLabelTextoSelecCat.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabelTextoSelecCat.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoSelecCat.setText("2- Selecciona la categoría de los chistes:");

        jLabelTextoSelectCant.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabelTextoSelectCant.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoSelectCant.setText("3- Selecciona la cantidad de chistes a mostrar (de 1 a 10) :");

        jRadioButtonProg.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonProg.setSelected(true);
        jRadioButtonProg.setText("Programming");
        jRadioButtonProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonProgActionPerformed(evt);
            }
        });

        jRadioButtonMisc.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMisc.setText("Misc");

        jRadioButtonPun.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonPun.setText("Pun");

        jRadioButtonDark.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonDark.setText("Dark");
        jRadioButtonDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDarkActionPerformed(evt);
            }
        });

        jRadioButtonSpooky.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSpooky.setText("Spooky");

        jRadioButtonChrist.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonChrist.setText("Christmast");

        jLabelNumChistes.setBackground(new java.awt.Color(102, 102, 102));
        jLabelNumChistes.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabelNumChistes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumChistes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumChistes.setText("1");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GENERADOR DE CHISTES MALOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonProg)
                    .addComponent(jRadioButtonDark)
                    .addComponent(jRadioButtonMisc))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonPun)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jRadioButtonChrist))
                    .addComponent(jRadioButtonSpooky))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTextoSelecCat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTextoSelecIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTextoSelectCant, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNumChistes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTextoSelecIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelTextoSelecCat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonProg)
                    .addComponent(jRadioButtonPun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMisc)
                    .addComponent(jRadioButtonSpooky))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDark)
                    .addComponent(jRadioButtonChrist))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextoSelectCant, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumChistes, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDarkActionPerformed

    private void jRadioButtonProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonProgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonProgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNumChistes;
    private javax.swing.JLabel jLabelTextoSelecCat;
    private javax.swing.JLabel jLabelTextoSelecIdioma;
    private javax.swing.JLabel jLabelTextoSelectCant;
    private javax.swing.JList<String> jListIdioma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonChrist;
    private javax.swing.JRadioButton jRadioButtonDark;
    private javax.swing.JRadioButton jRadioButtonMisc;
    private javax.swing.JRadioButton jRadioButtonProg;
    private javax.swing.JRadioButton jRadioButtonPun;
    private javax.swing.JRadioButton jRadioButtonSpooky;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
